#!/bin/bash

ghc --make agdatomd.hs

generatemd () {
    cat HoTT-UF-Agda.lagda | ./agdatomd > HoTT-UF-Agda.md
    cp HoTT-UF-Agda.md index.md
    cat Universes.lagda    | ./agdatomd > Universes.md
    }

generatemd

inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
    if [ "$filename" = "HoTT-UF-Agda.lagda" ] ||
       [ "$filename" = "Universes.lagda" ] ; then
      date
      generatemd
      echo "done"
  fi
done
