#!/bin/bash

mkdir -p pdf/all

google-chrome --headless --disable-gpu --print-to-pdf="pdf/index.pdf"        https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/index.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/toc.pdf"          https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/toc.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/MLTT-Agda.pdf"    https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/MLTT-Agda.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/HoTT-UF-Agda.pdf" https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/HoTT-UF-Agda.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/FunExt.pdf"       https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/FunExt.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/Inhabitation.pdf" https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/Inhabitation.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/Appendix.pdf"     https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/Appendix.html
google-chrome --headless --disable-gpu --print-to-pdf="pdf/Universes.pdf"    https://www.cs.bham.ac.uk/~mhe/HoTT-UF-in-Agda-Lecture-Notes/Universes.html

pdftk pdf/index.pdf pdf/toc.pdf pdf/MLTT-Agda.pdf pdf/HoTT-UF-Agda.pdf pdf/FunExt.pdf pdf/Inhabitation.pdf pdf/Appendix.pdf pdf/Universes.pdf output pdf/all/HoTT-UF-Agda.pdf

cp pdf/all/HoTT-UF-Agda.pdf ~/public_html/HoTT-UF-in-Agda-Lecture-Notes/
