#!/bin/bash

agda --html --html-highlight=code HoTT-UF-Agda.lagda

cd html
sed -i "s|Agda.Primitive.html|Universes.html|" *tex
cd ..

cp html/HoTT-UF-Agda.tex   index.md
mv html/HoTT-UF-Agda.tex   HoTT-UF-Agda.md
mv html/Universes.tex      Universes.md
