#!/bin/bash

mkdir -p pdf/all

google-chrome --headless --print-to-pdf="pdf/all/HoTT-UF-Agda.pdf" _site/HoTT-UF-Agda.html

# # You may need "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0" before the following

# pdftk pdf/HoTT-UF-Agda.pdf pdf/Universes.pdf output pdf/all/HoTT-UF-Agda.pdf

cp pdf/all/HoTT-UF-Agda.pdf ~/public_html/HoTT-UF-in-Agda-Lecture-Notes/
